$content = Get-Content "js\app.js"

$index = 0

for ($i = 0; $i -lt $content.Length; $i++) {

  if ($content[$i] -eq "];") {

    $index = $i

    break

  }

}

$newLines = @"

  {fi:"Auto", en:"Car", ph:"au-toh", cat:"transport", ex:"Auto on punainen. / The car is red.", starter:true},
  {fi:"Juna", en:"Train", ph:"yu-nah", cat:"transport", ex:"Juna tulee. / The train is coming.", starter:true},
  {fi:"Lentokone", en:"Airplane", ph:"len-toh-ko-neh", cat:"transport", ex:"Lentokone lentää. / The airplane flies.", starter:true},
  {fi:"Pyörä", en:"Bicycle", ph:"pü-ör-ä", cat:"transport", ex:"Pyörä on nopea. / The bicycle is fast.", starter:true},
  {fi:"Taksi", en:"Taxi", ph:"tak-si", cat:"transport", ex:"Otan taksin. / I take a taxi.", starter:true},
  {fi:"Metro", en:"Metro", ph:"meh-troh", cat:"transport", ex:"Metro on täynnä. / The metro is full.", starter:true},
  {fi:"Laiva", en:"Ship", ph:"lay-vah", cat:"transport", ex:"Laiva on iso. / The ship is big.", starter:true},
  {fi:"Lentokenttä", en:"Airport", ph:"len-toh-kent-tä", cat:"transport", ex:"Lentokenttä on kaukana. / The airport is far.", starter:true},
  {fi:"Asema", en:"Station", ph:"ah-seh-mah", cat:"transport", ex:"Asema on lähellä. / The station is near.", starter:true},
  {fi:"Lippu", en:"Ticket", ph:"lip-pu", cat:"transport", ex:"Ostan lipun. / I buy a ticket.", starter:true},
  {fi:"Matkalaukku", en:"Suitcase", ph:"mat-kah-lauk-ku", cat:"transport", ex:"Matkalaukku on painava. / The suitcase is heavy.", starter:true},
  {fi:"Kartta", en:"Map", ph:"kar-tah", cat:"transport", ex:"Katson karttaa. / I look at the map.", starter:true},
  {fi:"Tie", en:"Road", ph:"ti-eh", cat:"transport", ex:"Tie on pitkä. / The road is long.", starter:true},
  {fi:"Polkupyörä", en:"Bike", ph:"pol-ku-pü-ör-ä", cat:"transport", ex:"Polkupyörä on hyvä. / The bike is good.", starter:true},
  {fi:"Moottoripyörä", en:"Motorcycle", ph:"mo-oh-tor-i-pü-ör-ä", cat:"transport", ex:"Moottoripyörä on nopea. / The motorcycle is fast.", starter:true},
  {fi:"Raitiovaunu", en:"Tram", ph:"ray-ti-oh-vah-nu", cat:"transport", ex:"Raitiovaunu tulee. / The tram is coming.", starter:true},
  {fi:"Vene", en:"Boat", ph:"veh-neh", cat:"transport", ex:"Vene on järvellä. / The boat is on the lake.", starter:true},
  {fi:"Lentäjä", en:"Pilot", ph:"len-tä-yä", cat:"transport", ex:"Lentäjä lentää. / The pilot flies.", starter:true},
  {fi:"Kuljettaja", en:"Driver", ph:"kul-yet-tah-yah", cat:"transport", ex:"Kuljettaja ajaa. / The driver drives.", starter:true},
  {fi:"Lääkäri", en:"Doctor", ph:"lä-ä-kä-ri", cat:"health", ex:"Lääkäri auttaa. / The doctor helps.", starter:true},
  {fi:"Sairaanhoitaja", en:"Nurse", ph:"sai-raan-hoi-tah-yah", cat:"health", ex:"Sairaanhoitaja hoitaa. / The nurse cares.", starter:true},
  {fi:"Apteekki", en:"Pharmacy", ph:"ap-te-ek-ki", cat:"health", ex:"Apteekki on auki. / The pharmacy is open.", starter:true},
  {fi:"Lääke", en:"Medicine", ph:"lä-ä-keh", cat:"health", ex:"Otan lääkkeen. / I take medicine.", starter:true},
  {fi:"Kipu", en:"Pain", ph:"ki-pu", cat:"health", ex:"Minulla on kipu. / I have pain.", starter:true},
  {fi:"Kuume", en:"Fever", ph:"ku-veh-meh", cat:"health", ex:"Minulla on kuume. / I have a fever.", starter:true},
  {fi:"Yskä", en:"Cough", ph:"üs-kä", cat:"health", ex:"Yskä on paha. / The cough is bad.", starter:true},
  {fi:"Flunssa", en:"Flu", ph:"flun-sah", cat:"health", ex:"Minulla on flunssa. / I have the flu.", starter:true},
  {fi:"Hammaslääkäri", en:"Dentist", ph:"ham-mas-lä-ä-kä-ri", cat:"health", ex:"Hammaslääkäri tarkistaa. / The dentist checks.", starter:true},
  {fi:"Verenpaine", en:"Blood pressure", ph:"veh-ren-pay-neh", cat:"health", ex:"Verenpaine on korkea. / The blood pressure is high.", starter:true},
  {fi:"Rokotus", en:"Vaccination", ph:"roh-ko-tus", cat:"health", ex:"Saan rokotuksen. / I get a vaccination.", starter:true},
  {fi:"Terveys", en:"Health", ph:"ter-veys", cat:"health", ex:"Terveys on tärkeä. / Health is important.", starter:true},
  {fi:"Hoito", en:"Treatment", ph:"hoy-toh", cat:"health", ex:"Hoito auttaa. / The treatment helps.", starter:true},
  {fi:"Oire", en:"Symptom", ph:"oy-reh", cat:"health", ex:"Oireet ovat pahat. / The symptoms are bad.", starter:true},
  {fi:"Hammas", en:"Tooth", ph:"ham-mas", cat:"health", ex:"Hammas sattuu. / The tooth hurts.", starter:true},
  {fi:"Silmä", en:"Eye", ph:"sil-mä", cat:"health", ex:"Silmä on sininen. / The eye is blue.", starter:true},
  {fi:"Korva", en:"Ear", ph:"kor-vah", cat:"health", ex:"Korva kuulee. / The ear hears.", starter:true},
  {fi:"Nenä", en:"Nose", ph:"neh-ä", cat:"health", ex:"Nenä on pitkä. / The nose is long.", starter:true},
  {fi:"Talo", en:"House", ph:"tah-loh", cat:"home", ex:"Talo on iso. / The house is big.", starter:true},
  {fi:"Asunto", en:"Apartment", ph:"ah-sun-toh", cat:"home", ex:"Asunto on pieni. / The apartment is small.", starter:true},
  {fi:"Keittiö", en:"Kitchen", ph:"key-ti-ö", cat:"home", ex:"Keittiö on siisti. / The kitchen is clean.", starter:true},
  {fi:"Olohuone", en:"Living room", ph:"oh-loh-hu-oh-neh", cat:"home", ex:"Olohuone on lämmin. / The living room is warm.", starter:true},
  {fi:"Makuuhuone", en:"Bedroom", ph:"mah-ku-hu-oh-neh", cat:"home", ex:"Makuuhuone on hiljainen. / The bedroom is quiet.", starter:true},
  {fi:"Kylpyhuone", en:"Bathroom", ph:"kül-pü-hu-oh-neh", cat:"home", ex:"Kylpyhuone on kylmä. / The bathroom is cold.", starter:true},
  {fi:"Sänky", en:"Bed", ph:"sän-kü", cat:"home", ex:"Sänky on pehmeä. / The bed is soft.", starter:true},
  {fi:"Pöytä", en:"Table", ph:"pöy-tä", cat:"home", ex:"Pöytä on puinen. / The table is wooden.", starter:true},
  {fi:"Tuoli", en:"Chair", ph:"tu-oh-li", cat:"home", ex:"Tuoli on mukava. / The chair is comfortable.", starter:true},
  {fi:"Kaappi", en:"Cabinet", ph:"kaap-pi", cat:"home", ex:"Kaappi on täynnä. / The cabinet is full.", starter:true},
  {fi:"Ovi", en:"Door", ph:"oh-vi", cat:"home", ex:"Ovi on auki. / The door is open.", starter:true},
  {fi:"Ikkuna", en:"Window", ph:"ik-ku-nah", cat:"home", ex:"Ikkuna on puhdas. / The window is clean.", starter:true},
  {fi:"Lattia", en:"Floor", ph:"lat-ti-ah", cat:"home", ex:"Lattia on kylmä. / The floor is cold.", starter:true},
  {fi:"Katto", en:"Ceiling", ph:"kat-toh", cat:"home", ex:"Katto on korkea. / The ceiling is high.", starter:true},
  {fi:"Puutarha", en:"Garden", ph:"pu-tar-hah", cat:"home", ex:"Puutarha on kaunis. / The garden is beautiful.", starter:true},
  {fi:"Pesukone", en:"Washing machine", ph:"peh-su-ko-neh", cat:"home", ex:"Pesukone pesee. / The washing machine washes.", starter:true},
  {fi:"Liesi", en:"Stove", ph:"li-eh-si", cat:"home", ex:"Liesi on kuuma. / The stove is hot.", starter:true},
  {fi:"Jääkaappi", en:"Refrigerator", ph:"yä-kahp-pi", cat:"home", ex:"Jääkaappi on kylmä. / The refrigerator is cold.", starter:true},
  {fi:"Mikroaaltouuni", en:"Microwave", ph:"mi-kroh-al-toh-ou-ni", cat:"home", ex:"Mikroaaltouuni lämmittää. / The microwave heats.", starter:true},
  {fi:"Televisio", en:"Television", ph:"teh-leh-vi-sio", cat:"home", ex:"Televisio on päällä. / The television is on.", starter:true},
  {fi:"Aurinko", en:"Sun", ph:"au-rin-koh", cat:"weather", ex:"Aurinko paistaa. / The sun shines.", starter:true},
  {fi:"Pilvi", en:"Cloud", ph:"pil-vi", cat:"weather", ex:"Pilvi on valkoinen. / The cloud is white.", starter:true},
  {fi:"Sade", en:"Rain", ph:"sah-deh", cat:"weather", ex:"Sade tulee. / The rain is coming.", starter:true},
  {fi:"Lumi", en:"Snow", ph:"lu-mi", cat:"weather", ex:"Lumi sataa. / The snow falls.", starter:true},
  {fi:"Tuuli", en:"Wind", ph:"tu-u-li", cat:"weather", ex:"Tuuli puhaltaa. / The wind blows.", starter:true},
  {fi:"Ukkonen", en:"Thunder", ph:"uk-koh-nen", cat:"weather", ex:"Ukkonen jyrisee. / The thunder rumbles.", starter:true},
  {fi:"Salama", en:"Lightning", ph:"sah-lah-mah", cat:"weather", ex:"Salama välähtää. / The lightning flashes.", starter:true},
  {fi:"Sää", en:"Weather", ph:"sä-ä", cat:"weather", ex:"Sää on hyvä. / The weather is good.", starter:true},
  {fi:"Kuuma", en:"Hot", ph:"ku-u-mah", cat:"weather", ex:"Ilma on kuuma. / The air is hot.", starter:true},
  {fi:"Kylmä", en:"Cold", ph:"kül-mä", cat:"weather", ex:"Ilma on kylmä. / The air is cold.", starter:true},
  {fi:"Koulu", en:"School", ph:"koh-lu", cat:"education", ex:"Koulu on lähellä. / The school is near.", starter:true},
  {fi:"Opettaja", en:"Teacher", ph:"oh-pet-tah-yah", cat:"education", ex:"Opettaja opettaa. / The teacher teaches.", starter:true},
  {fi:"Oppilas", en:"Student", ph:"op-pi-las", cat:"education", ex:"Oppilas oppii. / The student learns.", starter:true},
  {fi:"Kirja", en:"Book", ph:"kir-yah", cat:"education", ex:"Kirja on mielenkiintoinen. / The book is interesting.", starter:true},
  {fi:"Kynä", en:"Pen", ph:"kün-ä", cat:"education", ex:"Kynä on musta. / The pen is black.", starter:true},
  {fi:"Paperi", en:"Paper", ph:"pah-peh-ri", cat:"education", ex:"Paperi on valkoinen. / The paper is white.", starter:true},
  {fi:"Luokka", en:"Classroom", ph:"lu-ok-kah", cat:"education", ex:"Luokka on täynnä. / The classroom is full.", starter:true},
  {fi:"Tentti", en:"Exam", ph:"ten-ti", cat:"education", ex:"Tentti on vaikea. / The exam is difficult.", starter:true},
  {fi:"Arvosana", en:"Grade", ph:"ar-voh-sah-nah", cat:"education", ex:"Arvosana on hyvä. / The grade is good.", starter:true},
  {fi:"Oppikirja", en:"Textbook", ph:"op-pi-kir-yah", cat:"education", ex:"Oppikirja on painava. / The textbook is heavy.", starter:true},
  {fi:"Koulutus", en:"Education", ph:"koh-lu-tus", cat:"education", ex:"Koulutus on tärkeä. / Education is important.", starter:true},
  {fi:"Kurssi", en:"Course", ph:"kur-si", cat:"education", ex:"Kurssi on pitkä. / The course is long.", starter:true},
  {fi:"Tutkinto", en:"Degree", ph:"tut-kin-toh", cat:"education", ex:"Tutkinto on valmis. / The degree is ready.", starter:true},
  {fi:"Yliopisto", en:"University", ph:"ü-li-oh-pis-toh", cat:"education", ex:"Yliopisto on iso. / The university is big.", starter:true},
  {fi:"Kirjasto", en:"Library", ph:"kir-yas-toh", cat:"education", ex:"Kirjasto on hiljainen. / The library is quiet.", starter:true},
  {fi:"Oppitunti", en:"Lesson", ph:"op-pi-tun-ti", cat:"education", ex:"Oppitunti alkaa. / The lesson starts.", starter:true},
  {fi:"Harjoitus", en:"Exercise", ph:"har-yoy-tus", cat:"education", ex:"Harjoitus on helppo. / The exercise is easy.", starter:true},
  {fi:"Tutkimus", en:"Research", ph:"tut-ki-mus", cat:"education", ex:"Tutkimus jatkuu. / The research continues.", starter:true},
  {fi:"Diplom", en:"Diploma", ph:"di-plo-mi", cat:"education", ex:"Diplom on seinällä. / The diploma is on the wall.", starter:true},
  {fi:"Urheilu", en:"Sport", ph:"ur-hei-lu", cat:"hobbies", ex:"Urheilu on hauskaa. / Sport is fun.", starter:true},
  {fi:"Musiikki", en:"Music", ph:"mu-si-ik-ki", cat:"hobbies", ex:"Musiikki soi. / The music plays.", starter:true},
  {fi:"Taide", en:"Art", ph:"tay-deh", cat:"hobbies", ex:"Taide on kaunis. / Art is beautiful.", starter:true},
  {fi:"Lukeminen", en:"Reading", ph:"lu-ke-mi-nen", cat:"hobbies", ex:"Lukeminen rentouttaa. / Reading relaxes.", starter:true},
  {fi:"Matkustaminen", en:"Traveling", ph:"mat-kus-tah-mi-nen", cat:"hobbies", ex:"Matkustaminen on jännittävää. / Traveling is exciting.", starter:true},
  {fi:"Valokuvaus", en:"Photography", ph:"vah-loh-ku-vah-us", cat:"hobbies", ex:"Valokuvaus on harrastus. / Photography is a hobby.", starter:true},
  {fi:"Ruuanlaitto", en:"Cooking", ph:"ru-an-lay-toh", cat:"hobbies", ex:"Ruuanlaitto on hauskaa. / Cooking is fun.", starter:true},
  {fi:"Puutarhanhoito", en:"Gardening", ph:"pu-tar-han-hoy-toh", cat:"hobbies", ex:"Puutarhanhoito rentouttaa. / Gardening relaxes.", starter:true},
  {fi:"Tanssi", en:"Dance", ph:"tan-si", cat:"hobbies", ex:"Tanssi on kaunis. / Dance is beautiful.", starter:true},
  {fi:"Elokuva", en:"Movie", ph:"eh-loh-ku-vah", cat:"hobbies", ex:"Elokuva on hyvä. / The movie is good.", starter:true},
  {fi:"Teatteri", en:"Theater", ph:"teh-at-teh-ri", cat:"hobbies", ex:"Teatteri on mielenkiintoinen. / Theater is interesting.", starter:true},
  {fi:"Käsityö", en:"Craft", ph:"kä-si-tü-ö", cat:"hobbies", ex:"Käsityö on luova. / Craft is creative.", starter:true},
  {fi:"Kalastus", en:"Fishing", ph:"kah-las-tus", cat:"hobbies", ex:"Kalastus on rauhallista. / Fishing is peaceful.", starter:true},
  {fi:"Vaellus", en:"Hiking", ph:"vah-el-lus", cat:"hobbies", ex:"Vaellus on hyvä liikunta. / Hiking is good exercise.", starter:true},
  {fi:"Pyöräily", en:"Cycling", ph:"pü-ör-äi-lü", cat:"hobbies", ex:"Pyöräily on hauskaa. / Cycling is fun.", starter:true},
  {fi:"Piirtäminen", en:"Drawing", ph:"pi-ir-tä-mi-nen", cat:"hobbies", ex:"Piirtäminen on luova. / Drawing is creative.", starter:true},
  {fi:"Laulaminen", en:"Singing", ph:"lau-lah-mi-nen", cat:"hobbies", ex:"Laulaminen on hauskaa. / Singing is fun.", starter:true},
  {fi:"Soittaminen", en:"Playing (instrument)", ph:"soy-tah-mi-nen", cat:"hobbies", ex:"Soittaminen on vaikea. / Playing is difficult.", starter:true},
  {fi:"Kuntosali", en:"Gym", ph:"kun-toh-sah-li", cat:"hobbies", ex:"Kuntosali on hyvä. / The gym is good.", starter:true},
  {fi:"Uinti", en:"Swimming", ph:"uin-ti", cat:"hobbies", ex:"Uinti on hyvä liikunta. / Swimming is good exercise.", starter:true},
  {fi:"Matka", en:"Trip", ph:"mat-kah", cat:"travel", ex:"Matka on pitkä. / The trip is long.", starter:true},
  {fi:"Hotelli", en:"Hotel", ph:"ho-tel-li", cat:"travel", ex:"Hotelli on mukava. / The hotel is comfortable.", starter:true},
  {fi:"Lentolippu", en:"Flight ticket", ph:"len-toh-lip-pu", cat:"travel", ex:"Lentolippu on kallis. / The flight ticket is expensive.", starter:true},
  {fi:"Passi", en:"Passport", ph:"pas-si", cat:"travel", ex:"Passi on tärkeä. / The passport is important.", starter:true},
  {fi:"Viisumi", en:"Visa", ph:"vi-su-mi", cat:"travel", ex:"Viisumi on valmis. / The visa is ready.", starter:true},
  {fi:"Matkailu", en:"Tourism", ph:"mat-kay-lu", cat:"travel", ex:"Matkailu kasvaa. / Tourism is growing.", starter:true},
  {fi:"Retki", en:"Excursion", ph:"ret-ki", cat:"travel", ex:"Retki on hauska. / The excursion is fun.", starter:true},
  {fi:"Opas", en:"Guide", ph:"oh-pas", cat:"travel", ex:"Opas kertoo. / The guide tells.", starter:true},
  {fi:"Museo", en:"Museum", ph:"mu-seh-oh", cat:"travel", ex:"Museo on mielenkiintoinen. / The museum is interesting.", starter:true},
  {fi:"Kirkko", en:"Church", ph:"kirk-koh", cat:"travel", ex:"Kirkko on vanha. / The church is old.", starter:true},
  {fi:"Ravintola", en:"Restaurant", ph:"rah-vin-toh-lah", cat:"travel", ex:"Ravintola on hyvä. / The restaurant is good.", starter:true},
  {fi:"Pankki", en:"Bank", ph:"pank-ki", cat:"travel", ex:"Pankki on auki. / The bank is open.", starter:true},
  {fi:"Poliisi", en:"Police", ph:"poh-li-si", cat:"travel", ex:"Poliisi auttaa. / The police help.", starter:true},
  {fi:"Ranta", en:"Beach", ph:"ran-tah", cat:"travel", ex:"Ranta on kaunis. / The beach is beautiful.", starter:true},
  {fi:"Vuori", en:"Mountain", ph:"vu-oh-ri", cat:"travel", ex:"Vuori on korkea. / The mountain is high.", starter:true},
  {fi:"Järvi", en:"Lake", ph:"yär-vi", cat:"travel", ex:"Järvi on sininen. / The lake is blue.", starter:true},
  {fi:"Metsä", en:"Forest", ph:"mets-ä", cat:"travel", ex:"Metsä on vihreä. / The forest is green.", starter:true},
  {fi:"Saari", en:"Island", ph:"sah-ri", cat:"travel", ex:"Saari on pieni. / The island is small.", starter:true},
  {fi:"Kello", en:"Clock", ph:"kel-loh", cat:"daily", ex:"Kello on kahdeksan. / The clock is eight.", starter:true},
  {fi:"Avain", en:"Key", ph:"ah-vay-n", cat:"daily", ex:"Avain on taskussa. / The key is in the pocket.", starter:true},
  {fi:"Lompakko", en:"Wallet", ph:"lom-pak-koh", cat:"daily", ex:"Lompakko on pöydällä. / The wallet is on the table.", starter:true},
  {fi:"Ku", en:"Moon", ph:"ku", cat:"weather", ex:"Ku on täynnä. / The moon is full.", starter:true},
  {fi:"Tähti", en:"Star", ph:"täh-ti", cat:"weather", ex:"Tähti loistaa. / The star shines.", starter:true},
  {fi:"Maa", en:"Earth", ph:"mah", cat:"daily", ex:"Maa on pyöreä. / The earth is round.", starter:true},
  {fi:"Tuli", en:"Fire", ph:"tu-li", cat:"daily", ex:"Tuli on kuuma. / The fire is hot.", starter:true},

];

"@

$content[$index] = $newLines

Set-Content "js\app.js" $content